# Generated by Django 4.0 on 2021-12-13 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_alter_institutetype_name_alter_specialty_name'),
        ('assessment', '0003_rename_assessmentinfo_webassessmentinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteassessmentdetail',
            old_name='assessment_id',
            new_name='asessment',
        ),
        migrations.AlterField(
            model_name='webassessmentinfo',
            name='description',
            field=models.TextField(verbose_name='Assessment Description'),
        ),
        migrations.AlterField(
            model_name='webassessmentinfo',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute', verbose_name='Website of Institute to be assessed'),
        ),
        migrations.AlterField(
            model_name='webassessmentinfo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Assessment Name'),
        ),
    ]
