# Generated by Django 4.0 on 2021-12-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_rename_assessment_id_websiteassessmentdetail_asessment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteassessmentdetail',
            old_name='asessment',
            new_name='asessment_id',
        ),
    ]
