# Generated by Django 4.0 on 2021-12-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('framework', '0005_alter_item_created_at_alter_item_updated_at'),
        ('institute', '0009_alter_institutetype_name_alter_specialty_name'),
        ('authentication', '0004_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAssessmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Assessment Name')),
                ('description', models.TextField(verbose_name='Assessment Description')),
                ('created_at', models.TimeField(auto_now=True)),
                ('finish_at', models.TimeField(blank=True, null=True)),
                ('is_fininshed', models.BooleanField(default=False)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute', verbose_name='Website of Institute to be assessed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'verbose_name_plural': 'Web Assessment Info',
            },
        ),
        migrations.CreateModel(
            name='WebsiteAssessmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(auto_now=True)),
                ('updated_at', models.TimeField(auto_now_add=True)),
                ('value', models.BooleanField(default=False)),
                ('asessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.webassessmentinfo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.item')),
            ],
            options={
                'verbose_name_plural': 'Website Assessment Details',
            },
        ),
    ]
