# Generated by Django 4.0 on 2021-12-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteassessmentdetail',
            old_name='asessment',
            new_name='asessment_id',
        ),
    ]
