# Generated by Django 4.0 on 2021-12-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_rename_asessment_websiteassessmentdetail_asessment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteassessmentdetail',
            old_name='asessment_id',
            new_name='asessment',
        ),
    ]
