# Generated by Django 4.0 on 2021-12-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_rename_asessment_id_websiteassessmentdetail_asessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteassessmentdetail',
            old_name='asessment',
            new_name='assessment',
        ),
    ]
