# Generated by Django 4.0 on 2021-12-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_rename_asessment_websiteassessmentdetail_assessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webassessmentinfo',
            old_name='is_fininshed',
            new_name='is_finished',
        ),
    ]
