# Generated by Django 4.0 on 2021-12-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_rename_is_fininshed_webassessmentinfo_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webassessmentinfo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='webassessmentinfo',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websiteassessmentdetail',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='websiteassessmentdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
