# Generated by Django 4.0 on 2021-12-08 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='framework.dimension'),
        ),
    ]
