# Generated by Django 4.0 on 2021-12-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('EU', 'Europe'), ('AF', 'Africa'), ('NA', 'North America'), ('SA', 'South America'), ('AS', 'Asia'), ('AU', 'Australia')], default=1, max_length=225),
            preserve_default=False,
        ),
    ]
