# Generated by Django 4.0 on 2021-12-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_institute_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name_plural': 'Specialties'},
        ),
    ]
