# Generated by Django 4.0 on 2021-12-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_alter_specialty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='img',
            field=models.ImageField(null=True, upload_to='institute/'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='business_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=225),
        ),
    ]
