# Generated by Django 4.0 on 2021-12-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_institute_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='institute/'),
        ),
    ]
