# Generated by Django 4.0 on 2021-12-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_country_continent'),
        ('institute', '0006_alter_institute_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.country'),
        ),
        migrations.AddField(
            model_name='institute',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.province'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.city'),
        ),
    ]
