# Generated by Django 4.0 on 2021-12-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_country_continent'),
        ('institute', '0007_institute_country_institute_province_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institute',
            unique_together={('name', 'country')},
        ),
    ]
