# Generated by Django 4.0 on 2021-12-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_alter_institute_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutetype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
